version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: language_trainer_mongodb
    ports:
      - 27000:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myadmin
      - MONGO_INITDB_ROOT_PASSWORD=mypassword

volumes:
  mongodb_data:
